version: "3"
services:
  frontend:
        build: ./Frontend
        container_name: frontend
        stdin_open: true
        environment:
            BACKEND_Connection: http://backend:8080
        ports:
             - "3000:3000"
  backend:
        build: ./Backend
        container_name: backend
        environment:
         database: loizenaidb
         username: postgres
         password: 8850
         host: postgres
        ports:
            - "8080:8080"
  postgres:
            image: postgres:latest
            container_name: postgres
            ports:
                - "5432:5432"
            environment:
              POSTGRES_PASSWORD: 8850
              POSTGRES_USER: postgres
              POSTGRES_DB: loizenaidb
